AllCops:
  TargetRubyVersion: 2.0

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/SpaceAroundOperators:
  AllowForAlignment: true


Lint/InheritException:
  Exclude:
    - 'spec/support/exceptions.rb'


Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/PerceivedComplexity:
  Enabled: false


RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  # rspec thinks these should be in spec/retriable/
  # There is a SpecSuffixOnly option that should fix this
  # but it's being silently ignored
  Exclude:
    - 'spec/config_spec.rb'
    - 'spec/exponential_backoff_spec.rb'

RSpec/InstanceVariable:
  Exclude:
    - 'spec/retriable_spec.rb'


Style/Documentation:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
